// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
		int count = Integer.parseInt(args[0]);
		int over = 0;
		int under = 0;
		for (int i = 0; i < count; i++) {
			double r = Math.random();
			if (r > 0.5) {
				over++;
			} else {
				under++;
			}
		}
        System.out.println("> 0.5:  " + over + " times");
		System.out.println("<= 0.5: " + under + " times");
		if (over>0 && under>0){ 
			double ratio = (over < under) ? (((double)over)/under) : (((double)under)/over);
			System.out.println("Ratio:" + ratio);
			
	}
 }
}
